// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20210512072144_Mighration1")]
    partial class Mighration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WebApplication1.Models.TblProcess", b =>
                {
                    b.Property<int>("IN_PROCESS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DT_LASTUPDATED_ON")
                        .HasColumnType("datetime2");

                    b.Property<int>("IN_LASTUPDATED_By")
                        .HasColumnType("int");

                    b.Property<int>("IN_LAST_SEQ")
                        .HasColumnType("int");

                    b.Property<string>("VC_PROCESS_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IN_PROCESS_ID");

                    b.ToTable("TblProcess");
                });

            modelBuilder.Entity("WebApplication1.Models.TblQueue", b =>
                {
                    b.Property<int>("IN_QUEUE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TblProcess")
                        .HasColumnType("int");

                    b.Property<string>("VC_QUEUE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IN_QUEUE_ID");

                    b.HasIndex("TblProcess");

                    b.ToTable("TblQueue");
                });

            modelBuilder.Entity("WebApplication1.Models.TblQueue", b =>
                {
                    b.HasOne("WebApplication1.Models.TblProcess", "IN_PROCESS_ID")
                        .WithMany()
                        .HasForeignKey("TblProcess");
                });
#pragma warning restore 612, 618
        }
    }
}
